server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dropmessage
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  hikari:
    connection-timeout: 20000
    maximum-pool-size: 10
